auth/urls.py
from django.conf.urls import patterns, url
from auth import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.views import login, logout_then_login

auth_not_required = user_passes_test(lambda u: not u.is_authenticated(), login_url='/auth/success/')
auth_required = user_passes_test(lambda u: u.is_authenticated(), login_url='/auth/signin/')

urlpatterns = patterns('',
	url(r'^signin/$', auth_not_required(login), {'template_name' : 'auth/signin.html', 'extra_context' : {'next' : '/auth/success/'}}, name='signin'),
	url(r'^logout/$', logout_then_login, {'login_url' : '/auth/signin/'}, name='logout'),
	url(r'^signup/$', auth_not_required(views.signup), name='signup'),
	url(r'^success/$', TemplateView.as_view(template_name='auth/signin_complete.html'), name='success'),
    url(r'^denied/$', TemplateView.as_view(template_name='auth/denied.html'), name='denied'),
    url(r'^activate/(?P<key>\w+)/$', auth_not_required(views.activate), name='activate'),
    url(r'^reset/$', auth_not_required(views.reset), name='reset'),
    url(r'^pchange/$', auth_required(views.password_change), name='pchange'),
)

category/urls.py
from django.conf.urls import patterns, url
from category import views
from complaint.urls import manager_required

urlpatterns = patterns('',
	url(r'^sub/(?P<category_id>\d+)/$', views.get_category_list, name='category_list'),
    url(r'^report/(?P<region_id>\d+)/(?P<frm>\d{2}-\d{2}-\d{4})/(?P<to>\d{2}-\d{2}-\d{4})/$', manager_required(views.region_report), name='region_report'),
    url(r'^report/(?P<region_id>\d+)/(?P<city_id>\d+)/(?P<frm>\d{2}-\d{2}-\d{4})/(?P<to>\d{2}-\d{2}-\d{4})/$', manager_required(views.city_report), name='city_report'),
)

comment/urls.py
from django.conf.urls import patterns, url
from comment import views
from auth.urls import auth_required

urlpatterns = patterns('',
	url(r'^add/$', auth_required(views.CommentAddView.as_view()), name='add'),
)

complaint/urls.py
from django.conf.urls import patterns, url
from complaint import views
from django.contrib.auth.decorators import user_passes_test
from django.conf import settings
from auth.urls import auth_required

head_required = user_passes_test(lambda u: u.profile.role_id >= settings.HEAD, login_url='/auth/denied/')
manager_required = user_passes_test(lambda u: u.profile.role_id >= settings.MANAGER, login_url='/auth/denied/')
executor_required = user_passes_test(lambda u: u.profile.role_id >= settings.EXECUTOR, login_url='/auth/denied/')
user_required = user_passes_test(lambda u: u.profile.role_id >= settings.USER, login_url='/auth/denied/')

urlpatterns = patterns('',
	url(r'^add/$', auth_required(views.ComplaintAddView.as_view()), name='add'),
    url(r'^view/(?P<pk>\d+)/$', auth_required(views.ComplaintDetailView.as_view()), name='view'),
    url(r'^my/(?P<page>\d+)/$', auth_required(views.ComplaintListView.as_view()), name='my'),
    url(r'^manage/(?P<page>\d+)/$', auth_required(executor_required(views.ComplaintManageListView.as_view())), name='manage'),
    url(r'^manage/(?P<sort>\w+)/(?P<page>\d+)/$', auth_required(executor_required(views.ComplaintManageListView.as_view())), name='manage_sort'),
    url(r'^subscribe/$', auth_required(manager_required(views.subscribe)), name='subscribe'),
    url(r'^unsubscribe/$', auth_required(executor_required(views.unsubscribe)), name='unsubscribe'),
    url(r'^update/$', auth_required(executor_required(views.update)), name='update'),
    url(r'^rate/$', auth_required(user_required(views.RateView.as_view())), name='rate'),
    url(r'^report/(?P<region_id>\d+)/(?P<frm>\d{2}-\d{2}-\d{4})/(?P<to>\d{2}-\d{2}-\d{4})/$', manager_required(views.region_report), name='region_report'),
    url(r'^report/(?P<region_id>\d+)/(?P<city_id>\d+)/(?P<frm>\d{2}-\d{2}-\d{4})/(?P<to>\d{2}-\d{2}-\d{4})/$', manager_required(views.city_report), name='city_report'),
    url(r'^report/(?P<frm>\d{2}-\d{2}-\d{4})/(?P<to>\d{2}-\d{2}-\d{4})/$', head_required(views.kz_report), name='rating_kz_report'),
)

zhaloby/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from auth.urls import auth_not_required
from django.contrib.auth.views import login
from auth.views import AboutView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', auth_not_required(login), {'template_name' : 'auth/signin.html', 'extra_context' : {'next' : '/auth/success/'}}, name='signin'),
    # url(r'^zhaloby/', include('zhaloby.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^location/', include('location.urls', namespace='location')),
    url(r'^complaint/', include('complaint.urls', namespace='complaint')),
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^status/', include('status.urls', namespace='status')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rosetta/', include('rosetta.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

location/models.py
from django.db import models

# Create your models here.


class Region(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=50)
    region = models.ForeignKey(Region)

    def __unicode__(self):
        return self.name

templates/about.html
{% extends 'base.html' %}
{% block title %}  Наши контактные данные {% endblock %}

{% block content %}
        <h2>Наши контактные данные</h2>
        <h3>По вопросам сотрудничества</h3>
        <p>Директор проекта: Артык Кузьмин<br/>
        Email: <a href="mailto:artikkuzmin@gmail.com">artikkuzmin@gmail.com</a></p>
        <hr/>
        <h3>По техническим вопросам </h3>
        <p>Инженер проекта: Дархан Имангалиев<br/>
        Email: <a href="mailto:darkhan.imangaliev@gmail.com">darkhan.imangaliev@gmail.com</a></p>
        <hr/>
        <h3>Офис "Executive Consulting"</h3>
        <p>Адрес: Алматы 050013, Площадь Республики 15, офис 535</p>
        <script type="text/javascript" charset="utf-8" src="//api-maps.yandex.ru/services/constructor/1.0/js/?sid=AKtCFyTc712G5mknrg7GkXlziireBYVP&width=800&height=450"></script>
        <hr/>
{% endblock %}

templates/bar_report.html
<div>
    <hr>
    <h3>Выберите даты для генерации отчета</h3>
    <input type="text" id="date-from" class="datepicker" value="{{ from|date:'d/m/Y' }}"/> - <input type="text" id="date-to" class="datepicker" value="{{ to|date:'d/m/Y' }}"/>
    <input type="button" class="btn btn-success" value="Сгенерировать" id="generate-report-btn">
    <input type="hidden" id="generate-url" value="{{value}}">
</div>

templates/base.html
<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" >

	{% load static %}

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
        <title>
            {% block title %}Жалобы на Казахтелеком{% endblock %}
        </title>
        {% block css%}
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.raty.css' %}">
        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-default navbar-fixed" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    {% if user.is_authenticated %}
                        <a class="navbar-brand" href="{% url 'complaint:my' 1 %}">Казахтелеком</a>
                    {% else %}
                        <a class="navbar-brand" href="{% url 'auth:signin' %}">Казахтелеком</a>
                    {% endif %}
                </div>
                {% if user.is_authenticated %}
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Здравствуйте, {{ user.username }} <span class="caret"></span></a>
                          <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'complaint:add' %}">Пожаловаться <(-.-)></a></li>
                            <li><a href="{% url 'complaint:my' 1 %}">Список моих жалоб</a></li>
                            {% if user.profile.is_head %}
                                <li><a href="{% url 'complaint:rating_kz_report' '01-08-2014' '30-09-2014' %}">Статистика по стране</a></li>
                            {% elif user.profile.is_manager %}
                                <li><a href="{% url 'complaint:manage' 1 %}">Жалобы по региону</a></li>
                                <li><a href="{% url 'complaint:region_report' user.profile.region_id '01-08-2014' '30-09-2014' %}">Статистика по региону</a></li>
                            {% elif user.profile.is_executor %}
                                <li><a href="{% url 'complaint:manage' 1 %}">Жалобы адресованные мне</a></li>
                            {% endif %}
                            <li class="divider"></li>
                            <li><a href="{% url 'auth:pchange' %}">Изменить пароль</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
                          </ul>
                        </li>
                      </ul>
                    </div>
                {% else %}
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'auth:signin' %}">Войти</a></li>
                            <li><a href="{% url 'auth:signup' %}">Зарегестрироваться</a></li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </nav>

        <div class="container" >
            {% block content %} {% endblock %}
        </div>

        <div class="footer">
            <hr>
            <span>2014 © «Executive Consulting»</span>
            <span style="margin-left: 20px"><a href="/about/">Контакты</a></span>
        </div>

        {% block mustjs %}
        <script src="{% static 'js/jquery-1.11.1.js' %}"></script>
        <script src="{% static 'js/jquery.ui.js' %}"></script>
        <script src="{% static 'js/jquery.ui.datepicker-ru.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.raty.js' %}"></script>
        <script type="text/javascript">
            var ERROR_MESSAGE = "Упс, что-то пошло не так:( Сообщите об этой ошибке разработчику, прикрепите к отчету скриншот страницы";
             $(".datepicker" ).datepicker( $.datepicker.regional[ "ru" ] );
             $(".datepicker").datepicker({
                changeMonth: true,
                changeYear: true,
                showAnim: 'drop'
             });

             $("#generate-report-btn").click(function(e){
                if ($('#generate-url').length == 0) return;
                var url = $('#generate-url').val() + '/' + $('#date-from').val().split("/").join("-") + '/' + $('#date-to').val().split("/").join("-") + '/';
                window.location.href = url;
             })

             function getCookie(name){
                var cookieValue = null;
                if (document.cookie && document.cookie != '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = jQuery.trim(cookies[i]);
                        // Does this cookie string begin with the name we want?

                        if (cookie.substring(0, name.length + 1) == (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
             }
        </script>
        {% endblock %}
        {% block js %} {% endblock %}

    </body>
</html>

templates/chart.html
{% load custom_tags %}
<div style="padding-top: 40;padding-bottom:40px">
    {% load chart_tags %}
    {% chart %}
         chs={{ width }}x{{ height }}
         cht=p
         chco={{colors|join:','}}
         chds=0,160
         chd=t:{{ values|join:',' }}
         chl={{ values|join:'|' }}
         chdl={{ categories|space2plus|join:'|' }}
    {% endchart %}
</div>

templates/errors.html
{% if error_list %}
    <ol>
        {% for error in error_list %}
            <li class="error"><strong>{{ error | escape }}</strong></li>
        {% endfor %}
    </ol>
{% endif %}

templates/map_report.html
<div style="margin-top:20px;margin-bottom:20px;text-align:center;">
    {% load chart_tags %}
    {% chart %}
         chs=750x400
         cht=map
         chld={{codes|join:'|'}}
         chdl={{codes|join:'|'}}
         chco=FFFFFF|{{colors|join:'|'}}
         chtt=Статистика+по+Казахстану
         chts=000000,25,c
    {% endchart %}
</div>

templates/report.html
{% extends 'base.html' %}

{% block title %}  {% endblock %}

{% block content %}

{% block stat_title %}
{% endblock %}

{% include 'chart.html' with values=values categories=categories width=width height=height%}
{% block city_chart %}{% endblock %}
<input type="hidden" id="region_id" value="{{region.id}}"/>
<input type="hidden" id="from" value="{{from|date:'d-m-Y'}}"/>
<input type="hidden" id="to" value="{{to|date:'d-m-Y'}}"/>

{% include 'bar_report.html' with value=url from=from to=to %}
<hr>
{% block city %}

    <h3>Статистика в городах "{{ region.name }}" за период с {{from|date:"d/m/Y"}} по {{to|date:"d/m/Y"}}</h3>
    <hr>
    {% for city in city_list %}
        <div class="city-stat">
            <img src="/static/img/loader.gif" style="visibility:hidden" id="{{city.id}}_loader"/>
            {{city.name}}
            <a data-stat="{{ city.id }}_stat" href="#">(статистика)</a>
            <div id="{{ city.id }}_menu" style="display:none;"></div>
        </div>
    {% endfor %}
    <hr>
{% endblock %}
{% endblock %}

{% block js %}
{% endblock %}