auth/urls.py
from django.conf.urls import patterns, url
from auth import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.views import login, logout_then_login

auth_not_required = user_passes_test(lambda u: not u.is_authenticated(), login_url='/auth/success/')
auth_required = user_passes_test(lambda u: u.is_authenticated(), login_url='/auth/signin/')

urlpatterns = patterns('',
	url(r'^signin/$', auth_not_required(login), {'template_name' : 'auth/signin.html', 'extra_context' : {'next' : '/auth/success/'}}, name='signin'),
	url(r'^logout/$', logout_then_login, {'login_url' : '/auth/signin/'}, name='logout'),
	url(r'^signup/$', auth_not_required(views.signup), name='signup'),
	url(r'^success/$', TemplateView.as_view(template_name='auth/signin_complete.html'), name='success'),
    url(r'^denied/$', TemplateView.as_view(template_name='auth/denied.html'), name='denied'),
    url(r'^activate/(?P<key>\w+)/$', auth_not_required(views.activate), name='activate'),
    url(r'^reset/$', auth_not_required(views.reset), name='reset'),
    url(r'^pchange/$', auth_required(views.password_change), name='pchange'),
)

complaint/urls.py
from django.conf.urls import patterns, url
from complaint import views
from django.contrib.auth.decorators import user_passes_test
from django.conf import settings
from auth.urls import auth_required

head_required = user_passes_test(lambda u: u.profile.role_id >= settings.HEAD, login_url='/auth/denied/')
manager_required = user_passes_test(lambda u: u.profile.role_id >= settings.MANAGER, login_url='/auth/denied/')
executor_required = user_passes_test(lambda u: u.profile.role_id >= settings.EXECUTOR, login_url='/auth/denied/')
user_required = user_passes_test(lambda u: u.profile.role_id >= settings.USER, login_url='/auth/denied/')

urlpatterns = patterns('',
	url(r'^add/$', auth_required(views.ComplaintAddView.as_view()), name='add'),
    url(r'^view/(?P<pk>\d+)/$', auth_required(views.ComplaintDetailView.as_view()), name='view'),
    url(r'^my/(?P<page>\d+)/$', auth_required(views.ComplaintListView.as_view()), name='my'),
    url(r'^manage/(?P<page>\d+)/$', auth_required(executor_required(views.ComplaintManageListView.as_view())), name='manage'),
    url(r'^manage/(?P<sort>\w+)/(?P<page>\d+)/$', auth_required(executor_required(views.ComplaintManageListView.as_view())), name='manage_sort'),
    url(r'^subscribe/$', auth_required(manager_required(views.subscribe)), name='subscribe'),
    url(r'^unsubscribe/$', auth_required(executor_required(views.unsubscribe)), name='unsubscribe'),
    url(r'^update/$', auth_required(executor_required(views.update)), name='update'),
    url(r'^rate/$', auth_required(user_required(views.RateView.as_view())), name='rate'),
    url(r'^report/(?P<region_id>\d+)/(?P<frm>\d{2}-\d{2}-\d{4})/(?P<to>\d{2}-\d{2}-\d{4})/$', manager_required(views.region_report), name='region_report'),
    url(r'^report/(?P<region_id>\d+)/(?P<city_id>\d+)/(?P<frm>\d{2}-\d{2}-\d{4})/(?P<to>\d{2}-\d{2}-\d{4})/$', manager_required(views.city_report), name='city_report'),
    url(r'^report/(?P<frm>\d{2}-\d{2}-\d{4})/(?P<to>\d{2}-\d{2}-\d{4})/$', head_required(views.kz_report), name='rating_kz_report'),
)

zhaloby/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from auth.urls import auth_not_required
from django.contrib.auth.views import login
from auth.views import AboutView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', auth_not_required(login), {'template_name' : 'auth/signin.html', 'extra_context' : {'next' : '/auth/success/'}}, name='signin'),
    # url(r'^zhaloby/', include('zhaloby.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^location/', include('location.urls', namespace='location')),
    url(r'^complaint/', include('complaint.urls', namespace='complaint')),
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^status/', include('status.urls', namespace='status')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rosetta/', include('rosetta.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

category/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    parent = models.ForeignKey('self', null=True, blank=True)

    def __unicode__(self):
        return self.name

comment/models.py
from django.db import models
from datetime import datetime
from complaint.models import Complaint
from auth.models import User
# Create your models here.


class Comment(models.Model):
    text = models.TextField()
    date_created = models.DateTimeField(default=datetime.now)
    visible = models.BooleanField(default=True)
    complaint = models.ForeignKey(Complaint)
    user = models.ForeignKey(User)

complaint/models.py
from django.db import models
from status.models import Status, Scenario
from category.models import Category
from location.models import Region, City
from auth.models import User
from datetime import datetime

# Create your models here.


class Complaint(models.Model):
    title = models.CharField(max_length=512, blank=False)
    description = models.TextField(blank=False)
    mobile = models.CharField(max_length=16)
    home_phone = models.CharField(max_length=16)
    date_created = models.DateTimeField(default=datetime.now)
    date_expire = models.DateTimeField(blank=True, null=True)
    date_modified = models.DateTimeField(auto_now=True, default=datetime.now)
    status = models.ForeignKey(Status)
    category = models.ForeignKey(Category)
    region = models.ForeignKey(Region)
    city = models.ForeignKey(City)
    user = models.ForeignKey(User, related_name='user_key')
    scenario = models.ForeignKey(Scenario, related_name='scenario_key', default=1)
    ratio = models.FloatField(default=0)

    def __unicode__(self):
        return "%d %s" % (self.id, self.title)


class History(models.Model):
    date_created = models.DateTimeField(auto_now=True)
    email_text = models.TextField(blank=True, null=True)
    work_text = models.TextField(blank=True, null=True)
    complaint = models.ForeignKey(Complaint, related_name='complaint_key')
    status = models.ForeignKey(Status, related_name='status_key')
    user = models.ForeignKey(User, related_name='user_history_key')


class Responsible(models.Model):
    complaint = models.ForeignKey(Complaint, related_name='responsible_complaint_key')
    user = models.ForeignKey(User, related_name='user_responsible_key')

location/models.py
from django.db import models

# Create your models here.


class Region(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=10)

    def __unicode__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=50)
    region = models.ForeignKey(Region)

    def __unicode__(self):
        return self.name

status/models.py
from django.db import models

# Create your models here.


class Status(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name


class Scenario(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return self.name


class ScenarioStatus(models.Model):
    status = models.ForeignKey(Status)
    scenario = models.ForeignKey(Scenario)
    order = models.IntegerField(default=1)

    def __unicode__(self):
        return "%d) %s (%s)" % (self.order, self.scenario.name, self.status.name)

templates/complaint/executor_list.html
{% extends 'base.html' %}

{% block title %} Список жалоб на которые вы подписаны {% endblock %}

{% block content %}
<h2>Список жалоб на которые вы подписаны</h2>
<hr>
{% if complaint_list %}
      <div class="panel-sort">
          <span class="panel-sort-item">Новые жалобы</span>
          <span class="panel-sort-item">Последние измененные жалобы</span>
      </div>
      <table id="cars" class="table table-striped table-bordered table-condensed table-hover">
          <tr>
              <th>Заголовок жалобы</th>
              <th>Категория жалобы</th>
              <th>Текущий статус</th>
              <th>Дата подачи жалобы</th>
              <th>Регион, Город</th>
          </tr>
        {% for complaint in complaint_list %}
            <tr>
                <td><a href="{% url 'complaint:view' complaint.id %}">{{ complaint.title }}</a></td>
                <td>{{ complaint.category.name }}</td>
                <td>{{ complaint.status.name }}</td>
                <td>{{ complaint.date_created|date:"d/m/Y H:i:s" }}</td>
                <td>{{ complaint.region.name }}, {{ complaint.city.name }}</td>
            </tr>
        {% endfor %}
    </table>
    {% if is_paginated %}
        <ul class="pagination center">
          {% if page_obj.has_previous %}
            <li><a href="{% url 'complaint:manage_sort' sort  page_obj.previous_page_number %}">&laquo;</a></li>
          {% endif %}

          {% for page in page_obj.paginator.page_range %}
            {% ifequal page page_obj.number %}
                <li class="active"><a href="#">{{page}} <span class="sr-only">(current)</span></a></li>
            {% else %}
                <li><a href="{% url 'complaint:manage_sort' sort  page %}">{{page}} <span class="sr-only">(current)</span></a></li>
            {% endifequal %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li><a href="{% url 'complaint:manage_sort' sort page_obj.next_page_number %}">&raquo;</a></li>
          {% endif %}
        </ul>
    {% endif %}
{% else %}
    <p>Здесь еще нет жалоб :(</p>
{% endif %}
{% endblock %}

templates/complaint/form.html
{% extends 'base.html' %}

{% block title %} Подать жалобу на платформу {% endblock %}

{% block content %}
<form class="form-horizontal signup-form" action="/complaint/add/" method="POST">{% csrf_token %}

  {% for hidden in form.hidden_fields %}
	  {{ hidden }}
  {% endfor %}

  	<fieldset>
	<div id="legend">
	  <legend class="">Подать жалобу на платформу</legend>
	</div>

    <div class="control-group">
    <!-- Category -->
	  <label class="control-label" for="id_category">Категория жалобы</label>
	  <div class="controls">
        <select id="id_category">
            <option value="0">К какой категории относится жалоба</option>
            {% for category in category_list %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <select id="id_category1">

        </select>
        <select id="id_category2">

        </select>
        <input type="hidden" name="category_id" id="category_value_id"/>
		<p class="help-block">Выберите категорию для жалобы</p>
        {% include 'errors.html' with error_list=form.category_id.errors %}
	  </div>
	</div>

    <div class="control-group">
	  <!-- Title -->
	  <label class="control-label" for="title">Заголовок жалобы</label>
	  <div class="controls">
		<input type="text" id="title" name="title" placeholder="Заголовок жалобы" class="input-xlarge" value="{{ form.title.value|default:'' }}">
		<p class="help-block">Введите заголовок жалобы</p>
        {% include 'errors.html' with error_list=form.title.errors %}
	  </div>
	</div>

    <div class="control-group">
    <!-- Description -->
	  <label class="control-label" for="description">Описание жалобы</label>
	  <div class="controls">
        <textarea name="description" id="description" class="input-xlarge" rows="10">{{ form.description.value|default:'' }}</textarea>
		<p class="help-block">Опишите вкратце вашу жалобу</p>
        {% include 'errors.html' with error_list=form.description.errors %}
	  </div>
	</div>

    <div class="control-group">
	  <!-- Home phone -->
	  <label class="control-label" for="home_phone">Лицевой счет</label>
	  <div class="controls">
		<input type="text" id="home_phone" name="home_phone" placeholder="Лицевой счет" class="input-xlarge" value="{{ form.home_phone.value|default:'' }}">
		<p class="help-block">Введите лицевой счет: (0000000)</p>
        {% include 'errors.html' with error_list=form.home_phone.errors %}
	  </div>
	</div>

    <div class="control-group">
	  <!-- Mobile -->
	  <label class="control-label" for="mobile">Мобильный телефон</label>
	  <div class="controls">
		<input type="text" id="mobile" name="mobile" placeholder="Мобильный телефон" class="input-xlarge" value="{{ form.mobile.value|default:'' }}">
		<p class="help-block">Введите мобильный телфон: (+77020000000)</p>
        {% include 'errors.html' with error_list=form.mobile.errors %}
	  </div>
	</div>

    <div class="control-group">
    <!-- Region -->
	  <label class="control-label" for="id_region">Регион проживания</label>
	  <div class="controls">
        <select name="region_id" id="id_region">
            <option value="0">Выберите регион проживания</option>
            {% for region in region_list %}
                {% if region.id == user.profile.region_id %}
                    <option value="{{ region.id }}" selected>{{ region.name }}</option>
                {% else %}
                    <option value="{{ region.id }}">{{ region.name }}</option>
                {% endif %}
            {% endfor %}
        </select>
		<p class="help-block">Выберите регион проживания</p>
        {% include 'errors.html' with error_list=form.region_id.errors %}
	  </div>
	</div>

    <div class="control-group">
    <!-- City -->
	  <label class="control-label" for="id_city">Город проживания</label>
	  <div class="controls">
        <select name="city_id" id="id_city">
            <option value="0">Выберите город проживания</option>
            {% for city in city_list %}
                {% if city.id == user.profile.city_id %}
                    <option value="{{ city.id }}" selected>{{ city.name }}</option>
                {% else %}
                    <option value="{{ city.id }}">{{ city.name }}</option>
                {% endif %}
            {% endfor %}
        </select>
		<p class="help-block">Выберите город проживания</p>
        {% include 'errors.html' with error_list=form.city_id.errors %}
	  </div>
	</div>

	<div class="control-group">
	  <!-- Button -->
	  <div class="controls">
		<button class="btn btn-success">Пожаловаться!</button>
	  </div>
	</div>
  </fieldset>
</form>
{% endblock %}

{% load static %}

{% block js %}
<script src="{% static 'js/location.js' %}"></script>
<script src="{% static 'js/complaint.form.js' %}"></script>
{% endblock %}

templates/complaint/kz_report.html
{% extends 'base.html' %}

{% block title %}  Статистика в разрезе по оценкам обидчиков по всей стране за период с {{from|date:"d/m/Y"}} по {{to|date:"d/m/Y"}} {% endblock %}

{% block content %}

{% block stat_title %}
<h3>Статистика в разрезе по оценкам обидчиков по всей стране за период с {{from|date:"d/m/Y"}} по {{to|date:"d/m/Y"}}</h3>
<hr>
{% endblock %}

{% include 'map_report.html' with regions=region values=value colors=color codes=code%}
{% include 'bar_report.html' with value="/complaint/report" from=from to=to %}

<hr>
<div class="">
    <h3>Объяснение к цветам карты</h3>
    <div><span class="square" style="background: #{{GREY}};"></span> - нет жалоб или жалобы еще не оценены</div>
    <div><span class="square" style="background: #{{RED}};"></span> - средняя оценка в интервале [1; 2)</div>
    <div><span class="square" style="background: #{{YELLOW}};"></span> - средняя оценка в интервале [2; 3)</div>
    <div><span class="square" style="background: #{{BLUE}};"></span> - средняя оценка в интервале [3; 4)</div>
    <div><span class="square" style="background: #{{GREEN}};"></span> - средняя оценка в интервале [4; 5]</div>
</div>

<hr>
<h3>Детальнее по регионам Казахастана</h3>
{% for region in region_list %}
    <div><a href="/complaint/report/{{ region.id }}/{{ from|date:'d-m-Y' }}/{{ to|date:'d-m-Y' }}/">{{region.name}}</a></div>
{% endfor %}
{% endblock %}

{% block js %}
{% endblock %}

templates/complaint/list.html
{% extends 'base.html' %}

{% block title %} Список моих жалоб на платформе {% endblock %}

{% block content %}
<h2>Список моих жалоб на платформе</h2>
{% if complaint_list %}
      <table id="cars" class="table table-striped table-bordered table-condensed table-hover">
          <tr>
              <th>Заголовок жалобы</th>
              <th>Категория жалобы</th>
              <th>Текущий статус</th>
              <th>Дата подачи жалобы</th>
          </tr>
        {% for complaint in complaint_list %}
            <tr>
                <td><a href="{% url 'complaint:view' complaint.id %}">{{ complaint.title }}</a></td>
                <td>{{ complaint.category.name }}</td>
                <td>{{ complaint.status.name }}</td>
                <td>{{ complaint.date_created|date:"d/m/Y" }}</td>
            </tr>
        {% endfor %}
    </table>
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'complaint:my' page_obj.previous_page_number %}">Предыдущая</a>
                {% endif %}
                <span class="page-current">
                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'complaint:my' page_obj.next_page_number %}">Следующая</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% else %}
    <p>Здесь еще нет жалоб :(</p>
{% endif %}
{% endblock %}

templates/complaint/manager_list.html
{% extends 'base.html' %}

{% block title %} Список жалоб по вашему региону {% endblock %}

{% block content %}
<h2>Список жалоб по вашему региону</h2>
<hr>
{% if complaint_list %}
      <div class="panel-sort">
          <span class="panel-sort-item">
                <a href="{% url 'complaint:manage_sort' 'cretd' 1 %}" {% ifequal sort 'cretd' %} class="underline" {%endifequal%}>Новые жалобы</a>
          </span>
          <span class="panel-sort-item">
              <a href="{% url 'complaint:manage_sort' 'modfd' 1 %}" {% ifequal sort 'modfd' %} class="underline" {%endifequal%}>Последние измененные жалобы</a>
          </span>
      </div>
      <div class="clear"></div>
      <hr>
      <table id="cars" class="table table-striped table-bordered table-condensed table-hover">
          <tr>
              <th>Заголовок жалобы</th>
              <th>Категория жалобы</th>
              <th>Текущий статус</th>
              <th>Дата подачи жалобы</th>
              <th>Регион, Город</th>
          </tr>
        {% for complaint in complaint_list %}
            <tr>
                <td><a href="{% url 'complaint:view' complaint.id %}">{{ complaint.title }}</a></td>
                <td>{{ complaint.category.name }}</td>
                <td>{{ complaint.status.name }}</td>
                <td>{{ complaint.date_created|date:"d/m/Y H:i:s" }}</td>
                <td>{{ complaint.region.name }}, {{ complaint.city.name }}</td>
            </tr>
        {% endfor %}
    </table>
    {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li><a href="{% url 'complaint:manage_sort' sort  page_obj.previous_page_number %}">&laquo;</a></li>
          {% endif %}

          {% for page in page_obj.paginator.page_range %}
            {% ifequal page page_obj.number %}
                <li class="active"><a href="#">{{page}} <span class="sr-only">(current)</span></a></li>
            {% else %}
                <li><a href="{% url 'complaint:manage_sort' sort  page %}">{{page}} <span class="sr-only">(current)</span></a></li>
            {% endifequal %}
          {% endfor %}

          {% if page_obj.has_next %}
            <li><a href="{% url 'complaint:manage_sort' sort page_obj.next_page_number %}">&raquo;</a></li>
          {% endif %}
        </ul>
    {% endif %}
{% else %}
    <p>Здесь еще нет жалоб :(</p>
{% endif %}
{% endblock %}

templates/complaint/progress.html
<div class="progress">
  <div class="progress-bar
  {% if progress <= 25 %}
    progress-bar-danger
    progress-bar-striped
    active
  {% elif progress <= 50 %}
    progress-bar-warning
    progress-bar-striped
    active
  {% elif progress <= 90 %}
    progress-bar-info
    progress-bar-striped
    active
  {% elif progress <= 95 %}
    progress-bar-success
    progress-bar-striped
    active
  {% else %}
    progress-bar-success
  {% endif %}
  " role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress|floatformat:0 }}%">
    {{progress|floatformat:1}}%
  </div>
</div>

templates/complaint/report.html
{% extends 'report.html' %}
{% block title %} Статистика в разрезе по оценкам обидчиков региона "{{ region.name }}" за период с {{from|date:"d/m/Y"}} по {{to|date:"d/m/Y"}} {% endblock %}


{% block stat_title %}
<h3>Статистика в разрезе по оценкам обидчиков региона "{{ region.name }}" за период с {{from|date:"d/m/Y"}} по {{to|date:"d/m/Y"}}</h3>
<hr>
{% endblock %}
{% block city_chart%}
<h3>Средняя оценка обидчиков по обработке жалобы в городах "{{ region.name }}" за период с {{from|date:"d/m/Y"}} по {{to|date:"d/m/Y"}}</h3>
<hr>
{% load custom_tags %}
<div style="padding-top: 40;padding-bottom:40px">
    {% load chart_tags %}
    {% chart %}
         chs=750x400
         cht=bhs
         chxt=x,y
         chxl=0:|0|1|2|3|4|5|1:|{{city|reverse|space2plus|join:"|"}}
         chco={{rcolor|join:"|"}}
         chds=0,5
         chd=t:{{ average|join:"," }}
    {% endchart %}
    <!--chdl={{city|join:"|"}}-->
</div>

{% endblock %}
{% block js %}
<script type="text/javascript" src="/static/js/complaint.rating.report.js"></script>
{% endblock %}

templates/complaint/success.html
{% extends 'base.html' %}

{% block title %} Вы успешно подали жалобу {% endblock %}

{% block content %}
    <h2>Вы успешно подали жалобу</h2>
    <a href="{% url 'complaint:my' 1 %}">Список моих жалоб</a>
{% endblock %}